/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __lcmmessages_dat_vehicle_heartbeat_msg_hpp__
#define __lcmmessages_dat_vehicle_heartbeat_msg_hpp__

#include <vector>
#include "lcmmessages/header.hpp"
#include "lcmmessages/VehicleInformation.hpp"
#include "lcmmessages/ControlMode.hpp"

namespace lcmmessages
{

class dat_vehicle_heartbeat_msg
{
    public:
        lcmmessages::header hdr;

        lcmmessages::VehicleInformation vehicle_info;

        int8_t     state;

        lcmmessages::ControlMode control_mode;

        int8_t     is_controlled;

        int32_t    control_station_id;

        int16_t    monitor_count;

        std::vector< int32_t > monitoring_station_ids;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "dat_vehicle_heartbeat_msg"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int dat_vehicle_heartbeat_msg::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int dat_vehicle_heartbeat_msg::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int dat_vehicle_heartbeat_msg::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t dat_vehicle_heartbeat_msg::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* dat_vehicle_heartbeat_msg::getTypeName()
{
    return "dat_vehicle_heartbeat_msg";
}

int dat_vehicle_heartbeat_msg::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->hdr._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->vehicle_info._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->state, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->control_mode._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_controlled, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->control_station_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->monitor_count, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->monitor_count > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->monitoring_station_ids[0], this->monitor_count);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dat_vehicle_heartbeat_msg::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->hdr._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->vehicle_info._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->state, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->control_mode._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_controlled, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->control_station_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->monitor_count, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->monitor_count) {
        this->monitoring_station_ids.resize(this->monitor_count);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->monitoring_station_ids[0], this->monitor_count);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dat_vehicle_heartbeat_msg::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->hdr._getEncodedSizeNoHash();
    enc_size += this->vehicle_info._getEncodedSizeNoHash();
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += this->control_mode._getEncodedSizeNoHash();
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->monitor_count);
    return enc_size;
}

uint64_t dat_vehicle_heartbeat_msg::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == dat_vehicle_heartbeat_msg::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, dat_vehicle_heartbeat_msg::getHash };

    uint64_t hash = 0x049513067bd242d3LL +
         lcmmessages::header::_computeHash(&cp) +
         lcmmessages::VehicleInformation::_computeHash(&cp) +
         lcmmessages::ControlMode::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
